version: '3.8'


volumes:
  postgres_data:


services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: crablind1/yamdb_final:latest
    volumes:
      - ./yamdb_final:/srv/www/<project>
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    image: nginx:1.19.6
    container_name: yamdb_nginx
    volumes:
      - ./static:/srv/www/yamdb_final/static
      - ./media:/srv/www/yamdb_final/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - web